#!/usr/bin/env bash

set -euo pipefail

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
target_home=${HOME:?HOME must be set}
dry_run=false
backup=false
uninstall=false
restore=false
install_claude=true
install_codex=true
new_overlays=
conflicts=0
timestamp=$(date +%Y%m%d%H%M%S)
state_root="$target_home/.config/agentfiles"
overlays_file="$state_root/overlays"
backups_base="$state_root/backups"
backup_root="$backups_base/$timestamp"
generated_header='<!-- Generated by agentfiles install.sh; edit the source AGENTS.md files and rerun it. -->'
codex_prompt_limit=32768

usage() {
  cat <<'EOF'
Usage: ./install.sh [--dry-run] [--backup] [--claude | --codex]
                 [--overlay <repo>]... [--uninstall [--restore]]

  --dry-run        Show what would change
  --backup         Move conflicts under ~/.config/agentfiles/backups before linking
  --uninstall      Remove the prompts and skill links this script installed
  --restore        With --uninstall, move each path's newest backup back into place
  --claude         Install Claude Code links only
  --codex          Install Codex links only
  --overlay <repo> Add a private repo, remembered in ~/.config/agentfiles/overlays:
                   its AGENTS.md joins the base prompt and its skills are linked
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      dry_run=true
      ;;
    --backup)
      backup=true
      ;;
    --uninstall)
      uninstall=true
      ;;
    --restore)
      restore=true
      ;;
    --claude)
      install_claude=true
      install_codex=false
      ;;
    --codex)
      install_claude=false
      install_codex=true
      ;;
    --overlay)
      new_overlays+=$(CDPATH= cd -- "${2:?--overlay needs a path}" && pwd)$'\n'
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if $restore && ! $uninstall; then
  printf '%s\n' '--restore needs --uninstall' >&2
  exit 2
fi

# Print remembered overlays, then new ones, without duplicates.
overlay_roots() {
  {
    [[ -f "$overlays_file" ]] && cat "$overlays_file"
    printf '%s' "$new_overlays"
  } | awk 'NF && !seen[$0]++'
}

has_overlays() {
  [[ -n "$(overlay_roots)" ]]
}

# Every root that contributes skills, in link precedence order.
skill_roots() {
  printf '%s\n' "$repo_root"
  overlay_roots
}

describe_path() {
  local source=$1
  local destination=$2

  if [[ -L "$destination" && "$(readlink "$destination")" == "$source" ]]; then
    printf 'OK       %s\n' "$destination"
  elif [[ -L "$destination" && ! -e "$destination" ]]; then
    printf 'RELINK   %s -> %s\n' "$destination" "$source"
  elif [[ -e "$destination" || -L "$destination" ]]; then
    printf 'CONFLICT %s\n' "$destination"
    conflicts=$((conflicts + 1))
  else
    printf 'LINK     %s -> %s\n' "$destination" "$source"
  fi
}

# Print the generated prompt for a harness: Claude imports both files, Codex gets a copy.
render_prompt() {
  local harness=$1
  local root

  printf '%s\n\n' "$generated_header"
  if [[ "$harness" == claude ]]; then
    while IFS= read -r root; do
      [[ -f "$root/AGENTS.md" ]] || continue
      printf '@%s\n\n' "$root/AGENTS.md"
    done < <(skill_roots)
  else
    while IFS= read -r root; do
      [[ -f "$root/AGENTS.md" ]] || continue
      cat "$root/AGENTS.md"
      printf '\n'
    done < <(skill_roots)
  fi
}

is_generated_prompt() {
  local destination=$1

  [[ -f "$destination" && ! -L "$destination" ]] &&
    [[ "$(head -n 1 "$destination")" == "$generated_header" ]]
}

# Succeed if the prompt at a destination was installed by this script.
is_own_prompt() {
  local destination=$1

  [[ -L "$destination" && "$(readlink "$destination")" == "$repo_root/AGENTS.md" ]] ||
    is_generated_prompt "$destination"
}

describe_prompt() {
  local harness=$1
  local destination=$2
  local size

  if ! has_overlays; then
    if is_generated_prompt "$destination"; then
      printf 'LINK     %s -> %s\n' "$destination" "$repo_root/AGENTS.md"
    else
      describe_path "$repo_root/AGENTS.md" "$destination"
    fi
    return
  fi

  if is_generated_prompt "$destination" && cmp -s <(render_prompt "$harness") "$destination"; then
    printf 'OK       %s\n' "$destination"
  elif [[ ! -e "$destination" && ! -L "$destination" ]] || is_own_prompt "$destination"; then
    printf 'WRITE    %s\n' "$destination"
  else
    printf 'CONFLICT %s\n' "$destination"
    conflicts=$((conflicts + 1))
  fi

  if [[ "$harness" == codex ]]; then
    size=$(render_prompt "$harness" | wc -c | tr -d ' ')
    if [[ $size -gt $codex_prompt_limit ]]; then
      printf 'WARNING  %s is %d bytes, over the project_doc_max_bytes default of %d\n' \
        "$destination" "$size" "$codex_prompt_limit" >&2
    fi
  fi
}

# Print skill links whose target, inside a skill root, no longer exists.
dangling_links() {
  local skills_destination=$1
  local link
  local root

  [[ -d "$skills_destination" && ! -L "$skills_destination" ]] || return 0
  for link in "$skills_destination"/*; do
    [[ -L "$link" && ! -e "$link" ]] || continue
    while IFS= read -r root; do
      if [[ "$(readlink "$link")" == "$root/skills/"* ]]; then
        printf '%s\n' "$link"
      fi
    done < <(skill_roots)
  done
}

# Print each skill name that more than one root provides, with its sources.
duplicate_skills() {
  local root
  local skill_source

  while IFS= read -r root; do
    for skill_source in "$root"/skills/*; do
      [[ -d "$skill_source" ]] && printf '%s\t%s\n' "$(basename "$skill_source")" "$skill_source"
    done
  done < <(skill_roots) | awk -F '\t' '
    { sources[$1] = sources[$1] "\n  " $2; count[$1]++ }
    END { for (name in count) if (count[name] > 1) printf "%s:%s\n", name, sources[name] }
  '
}

describe_skill_root() {
  local destination=$1

  if [[ -L "$destination" || (-e "$destination" && ! -d "$destination") ]]; then
    printf 'CONFLICT %s\n' "$destination"
    conflicts=$((conflicts + 1))
  elif [[ ! -e "$destination" ]]; then
    printf 'MKDIR    %s\n' "$destination"
  fi
}

describe_harness() {
  local harness=$1
  local prompt_destination=$2
  local skills_destination=$3
  local root
  local skill_source

  describe_prompt "$harness" "$prompt_destination"
  describe_skill_root "$skills_destination"

  if [[ ! -L "$skills_destination" ]]; then
    while IFS= read -r root; do
      for skill_source in "$root"/skills/*; do
        [[ -d "$skill_source" ]] || continue
        describe_path "$skill_source" "$skills_destination/$(basename "$skill_source")"
      done
    done < <(skill_roots)
  fi

  dangling_links "$skills_destination" | sed 's/^/PRUNE    /'
}

backup_path() {
  local destination=$1
  local relative=${destination#"$target_home"/}
  local saved="$backup_root/$relative"

  mkdir -p "$(dirname "$saved")"
  printf 'BACKUP   %s -> %s\n' "$destination" "$saved"
  mv "$destination" "$saved"
}

link_path() {
  local source=$1
  local destination=$2

  if [[ -L "$destination" && "$(readlink "$destination")" == "$source" ]]; then
    return
  fi

  if [[ -L "$destination" && ! -e "$destination" ]]; then
    rm "$destination"
  elif [[ -e "$destination" || -L "$destination" ]]; then
    backup_path "$destination"
  fi

  mkdir -p "$(dirname "$destination")"
  ln -s "$source" "$destination"
  printf 'LINKED   %s -> %s\n' "$destination" "$source"
}

install_prompt() {
  local harness=$1
  local destination=$2
  local staged

  if ! has_overlays; then
    is_generated_prompt "$destination" && rm "$destination"
    link_path "$repo_root/AGENTS.md" "$destination"
    return
  fi

  if is_generated_prompt "$destination" && cmp -s <(render_prompt "$harness") "$destination"; then
    return
  fi

  if is_own_prompt "$destination"; then
    rm "$destination"
  elif [[ -e "$destination" || -L "$destination" ]]; then
    backup_path "$destination"
  fi

  mkdir -p "$(dirname "$destination")"
  staged=$(mktemp "$destination.XXXXXX")
  render_prompt "$harness" >"$staged"
  mv "$staged" "$destination"
  printf 'WROTE    %s\n' "$destination"
}

prepare_skill_root() {
  local destination=$1

  if [[ -L "$destination" || (-e "$destination" && ! -d "$destination") ]]; then
    backup_path "$destination"
  fi
  mkdir -p "$destination"
}

install_harness() {
  local harness=$1
  local prompt_destination=$2
  local skills_destination=$3
  local root
  local skill_source
  local link

  install_prompt "$harness" "$prompt_destination"
  prepare_skill_root "$skills_destination"
  while IFS= read -r root; do
    for skill_source in "$root"/skills/*; do
      [[ -d "$skill_source" ]] || continue
      link_path "$skill_source" "$skills_destination/$(basename "$skill_source")"
    done
  done < <(skill_roots)

  while IFS= read -r link; do
    rm "$link"
    printf 'PRUNED   %s\n' "$link"
  done < <(dangling_links "$skills_destination")
}

save_overlays() {
  local staged

  [[ -n "$new_overlays" ]] || return 0
  mkdir -p "$state_root"
  staged=$(mktemp "$overlays_file.XXXXXX")
  overlay_roots >"$staged"
  mv "$staged" "$overlays_file"
}

# Print each installed path: own prompts, then skill links into a skill root.
installed_paths() {
  local prompt_destination=$1
  local skills_destination=$2
  local link
  local root

  is_own_prompt "$prompt_destination" && printf '%s\n' "$prompt_destination"
  [[ -d "$skills_destination" && ! -L "$skills_destination" ]] || return 0
  for link in "$skills_destination"/*; do
    [[ -L "$link" ]] || continue
    while IFS= read -r root; do
      if [[ "$(readlink "$link")" == "$root/skills/"* ]]; then
        printf '%s\n' "$link"
      fi
    done < <(skill_roots)
  done
}

# Print the newest backup of a destination, if any.
latest_backup() {
  local destination=$1
  local relative=${destination#"$target_home"/}
  local saved

  for saved in "$backups_base"/*/"$relative"; do
    if [[ -e "$saved" || -L "$saved" ]]; then
      printf '%s\n' "$saved"
    fi
  done | sort | tail -n 1
}

uninstall_harness() {
  local prompt_destination=$1
  local skills_destination=$2
  local destination
  local saved

  while IFS= read -r destination; do
    printf 'REMOVE   %s\n' "$destination"
    $dry_run || rm "$destination"
    $restore || continue
    saved=$(latest_backup "$destination")
    [[ -n "$saved" ]] || continue
    printf 'RESTORE  %s <- %s\n' "$destination" "$saved"
    $dry_run || mv "$saved" "$destination"
  done < <(installed_paths "$prompt_destination" "$skills_destination")
}

if $uninstall; then
  if $install_claude; then
    printf '%s\n' 'Claude Code'
    uninstall_harness "$target_home/.claude/CLAUDE.md" "$target_home/.claude/skills"
  fi
  if $install_codex; then
    printf '%s\n' 'Codex'
    uninstall_harness "$target_home/.codex/AGENTS.md" "$target_home/.agents/skills"
  fi
  exit 0
fi

duplicates=$(duplicate_skills)
if [[ -n "$duplicates" ]]; then
  printf 'Skill names must be unique across the base repo and overlays:\n%s\n' "$duplicates" >&2
  exit 1
fi

if $install_claude; then
  printf '%s\n' 'Claude Code'
  describe_harness claude "$target_home/.claude/CLAUDE.md" "$target_home/.claude/skills"
fi

if $install_codex; then
  printf '%s\n' 'Codex'
  describe_harness codex "$target_home/.codex/AGENTS.md" "$target_home/.agents/skills"
fi

if [[ $conflicts -gt 0 ]] && ! $backup; then
  printf '\n%d conflict(s); rerun with --backup to preserve and replace them.\n' "$conflicts" >&2
  exit 1
fi

if $dry_run; then
  exit 0
fi

if $install_claude; then
  install_harness claude "$target_home/.claude/CLAUDE.md" "$target_home/.claude/skills"
fi

if $install_codex; then
  install_harness codex "$target_home/.codex/AGENTS.md" "$target_home/.agents/skills"
fi

save_overlays
